version: "3.7"

services:
  apache:
    container_name: apache
    build:
      context: ./apache
      dockerfile: Dockerfile
    restart: on-failure
    links:
      - database
    volumes:
      - ./apache/src:/var/www/html
    ports:
      - "80:80"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: on-failure
    links:
      - database
    volumes:
      - ./nginx/src:/usr/share/nginx/html-static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"

  database:
    container_name: database
    image: mysql:8.0.30
    restart: on-failure
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: appDB
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  redis:
    container_name: redis
    image: redis:6.2.7
    command: redis-server
    restart: on-failure
    ports:
      - "6379:6379"

  spring:
    container_name: spring
    build:
      context: ./spring_pr8
      dockerfile: Dockerfile
    links:
      - database
      - redis
    volumes:
      - ./spring/src:/usr/src/app
    ports:
      - "8081:8081"